### ISSUE TITLE
Bad value causes full crash

### ISSUE THREAD

**Issue by googanhiem** [etheralm/libpurecool#28] opened 2020-11-23 23:44 UTC
Hi @etheralm,

Been having an issue with libpurecool in home assistant recently, so have others[ (Link to ha issue)](https://github.com/home-assistant/core/issues/41027). 

Looks like dyson_pure_state_v2.py isn’t retrying after getting a bad integer. It causes the whole component to fail, while still appearing operational. 

`Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:318 
First occurred: 14:10:17 (2 occurrences) 
Last logged: 17:57:16

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/libpurecool/dyson_pure_cool_link.py", line 104, in on_message
    device_msg = DysonEnvironmentalSensorV2State(payload)
  File "/usr/local/lib/python3.8/site-packages/libpurecool/dyson_pure_state_v2.py", line 157, in __init__
    else int(particulate_matter_25)
ValueError: invalid literal for int() with base 10: 'FAIL' `

**Comment by googanhiem** [comment] 2020-11-24 13:15
So I believe the issue is that dyson_pure_state_v2.py can’t handle non-integer values for pm2.5 and a couple other states. 

My fan for some reason (probably a recent firmware update) now sends a “FAIL” message instead of nothing on bad reads, which causes the script to fail.

An integer check of some sort needs to be added to the statement or to the const.py file. This might be above my skill level, ha.

**Comment by wizardels** [comment] 2020-11-24 13:47
Running into the same issue when using this on HomeAssistant

**Comment by wizardels** [comment] 2020-11-24 13:50
This should be fairly easy, is anyone willing to implement this? Happy to take a look if not 👍

**Comment by googanhiem** [comment] 2020-11-24 16:01
> This should be fairly easy, is anyone willing to implement this? Happy to take a look if not 👍

I would say go for it and file the PR. @etheralm only checks in occasionally and has approved a change of mine pretty quickly a while back.

**Comment by Mikeput** [comment] 2020-11-26 10:12
easy fix is to include 'FAIL' as in initial state in const.py e.g.

SENSOR_INIT_STATES = ['INIT', 'OFF', 'FAIL']

I don't use github so if someone can do honours to get it fixed.

**Comment by googanhiem** [comment] 2020-11-26 11:02
> easy fix is to include 'FAIL' as in initial state in const.py e.g.
> 
> SENSOR_INIT_STATES = ['INIT', 'OFF', 'FAIL']
> 
> I don't use github so if someone can do honours to get it fixed.

I’ve made the the changes to my fork if anyone wants to test it... I won’t be home to try it in a HA custom component for a while.

https://github.com/googanhiem/libpurecool

There may be other changes to the Dyson api we don’t know about that may throw up some errors. So please report back after 24hrs to tell us if it works. 

If it works I’m happy to file the PR.

**Comment by googanhiem** [comment] 2020-11-26 19:56
I tested my fork and it’s working without issue. Thanks @Mikeput!

Tomorrow I’ll file a PR.

**Comment by wizardels** [comment] 2020-11-27 09:37
Amazing thanks @googanhiem.

Was gonna get round to it, just been swamped! Let me know when you put the PR up

**Comment by etheralm** [comment] 2020-11-27 18:12
hey thanks a lot for the PR and sorry for the slow reply. I just merged it. I try to push a new version with it included to pypi tomorrow.

**Comment by DavidBurela** [comment] 2020-11-28 12:25
Thanks for your work on this one.  Started failing in HA for me a week ago after I set it up, but couldn't find any information back then.  Tried again this evening and found everyone has gotten to the root cause and triaged it. 
Thanks all!

**Comment by etheralm** [comment] 2020-11-30 18:04
ok I just pushed the new version to pypi. Give me a sec and I'll open a PR to bump the version of the library in home assistant.

**Comment by etheralm** [comment] 2020-11-30 18:19
I just opened a PR to bump the version in HA, you can track the progress here:
https://github.com/home-assistant/core/pull/43779

**Comment by frenck** [comment] 2020-12-01 13:39
ooh right, @etheralm, upstream you close the PR without anything and in here you complain about the "HA Maintainers". I think that that is very uncalled for and rude to say the least.

The only thing asked, was a to add a small link/reference to the PR description.

That is something we standardized and ask everybody. I'm not sure how adding a link to make your PR complete is a big deal / high level of mental energy. I do, however, learned a lot about this action.

But hey, thanks for your effort. 👍 

PS: For anybody reading this and want to know what the "deal" was he is talking about:
<https://github.com/home-assistant/core/pull/43779#issuecomment-735961682>

**Closed** 2020-12-01 13:41 UTC

**Comment by etheralm** [comment] 2020-12-01 13:42
Please try not to spam other projects.

**Comment by frenck** [comment] 2020-12-01 13:50
Just wow.

I'm sorry to hear something is wrong, I did not plan on spamming anything, not did IMHO spam (which is a bit unfair to me, to be honest).

Nevertheless, I'm open to discussing anything. I understand, based on your reaction you might not be up to that right now. But, my door is open for a chat any time 👍 

All the best.

../Frenck

**Comment by etheralm** [comment] 2020-12-01 14:10
I did not want to bring up this discussion in a ticket regarding a specific issue in another project, but I guess I can't stop you from doing it either, hence the "spam" comment. I didn't intend to make it feel unfair to you, but tbh it felt unfair that you came in posting your last rather offensive "to me" comment.

For me there is a reason why I left the last HA PR I opened unfinished. I guess it was unfair to dump it all on you right now since it had nothing to do with you, but I found it rather silly that  you ask in a "standard" message to post a git diff for something where I literally linked the issue discussing the fix and the PR for it right before your message. You were able to find it quite quickly after I gave your post a thumbs down. 

In the end it's your project, your rules. I'm not willing to follow them so I don't contribute. I still love HA and use it every day, but I don't try to come and force my opinion down your throats regarding the way you decided to run your project and I would feel rather nice if you don't do the same.

**Comment by holman** [comment] 2020-12-01 14:12
Whew. Talk about an overreaction. What a bummer.

**Comment by frenck** [comment] 2020-12-01 14:26
> I did not want to bring up this discussion in a ticket regarding a specific issue in another project

In all fairness, you did bring it up yourself by making a statement on the HA maintainers, in this case, it was me that commented. Hence, I feel addressed.

> I guess it was unfair to dump it all on you right now since it had nothing to do with you

Thanks, 👍  I appreciate that comment.

> You were able to find it quite quickly after I gave your post a thumbs down.

I found the fix. I didn't find the changes in the version bump. For example, I cannot see what else or which other commits/fixes were applied. Hence the fairly standard question (which most contributors actually provide by default). That said, your PR description was almost completely empty, which makes it hard to judge what I'm approving; yet it affects users of Home Assistant.

> I literally linked the issue discussing the fix and the PR for it right before your message

If you felt that way that strong, that could have simply been a reply on the PR as well, right?

> In the end it's your project, your rules. I'm not willing to follow them so I don't contribute.

That is your call and sorry to hear you don't like the rules as set up by the community/contributors of Home Assistant (as in, it is not my personal rules perse).

>  I don't try to come and force my opinion down your throats regarding the way you decided to run your project

I don't even know how to answer that or why this is necessary. I didn't contribute here, but if I would, I will definitely make sure I follow your standards.

You know, I don't want to point fingers at all. I'm just sad for people that actually would have benefitted from these fixes and the nice work that has done. To me, it feels like a rage quit because you have a different opinion.

But then again, you decide which projects you are willing to contribute to. I like contributing to HA, if you don't 🤷 

Stay safe.

../Frenck

**Comment by etheralm** [comment] 2020-12-01 14:45
Ok you just reminded me why I don't do this anymore. as I mentioned in the first post, the one you felt addressed in. I don't have the time/mental energy and I'll paraphrase it now: I don't have the time and mental energy to deal with this whole thing right now, not only with you.

One thing I think you just managed to achieve is to make me completely lose interest in contributing in any meaningful way to projects where I know I could otherwise help, even with my limited time and recourses. Don't take it as an accusation, I actually find it rather liberating. 

You obviously noticed that something is not right for me to respond like this and you are absolutely right. I have more than I can deal with on my plate right now and it has nothing to do with contributing to open source projects, but you still decided to push it further so you win, hurray? 

If someone is willing to pick up this one up, I'll be happy to transfer it to them. I would prefer not to abandon it like the last person, but maybe it's for the better.

Cheers.

**Comment by frenck** [comment] 2020-12-01 14:55
> but you still decided to push it further so you win, hurray?

Chill... all I asked for was a link... 🤷 

> I'll be happy to transfer it to them. I would prefer not to abandon it like the last person

That decent and generous. Appreciated and will keep my eyes open for that.

> I have more than I can deal with on my plate right now

I know what that is like (not trying to say you are going through the same thing or I know what it is like for you right now), nevertheless, I sincerely hope you'll find your way, piece, and space in it.

All the best 👍
